### ISSUE TITLE
Code for data

### ISSUE THREAD

**Issue by jgamper** [OATML/ucate#2]
https://github.com/OATML/ucate/blob/354f0821276dfdb8a67e157ffd00ea62034e0745/ucate/application/workflows/cevae.py#L7

Hi @anndvision , I might be completely blind but I am struggling to find code that generates CEMNIST and builds dataloaders for IHDP and ACIC 2016 anywhere in the repo. I see there is an import call, but I cannot find the module itself?

**Comment by anndvision** [comment]
Hi Jev,

You are right, it is missing. I will add this today.

**Comment by jgamper** [comment]
Thanks Andrew, look forward! Great work btw, very interesting

**Comment by anndvision** [comment]
Thanks a lot! And thanks for letting me know about the missing files. I've updated main. Let me know if it is working for you.

**Comment by jgamper** [comment]
Yeah - I see it now! Great, will check it out later, but will close the issue for now! Thank you
