### ISSUE TITLE
CATE computation

### ISSUE THREAD

**Issue by jgamper** [OATML/ucate#4]
https://github.com/OATML/ucate/blob/f57e47b1baec802c955adc7b07317d8014e50d91/ucate/library/utils/prediction.py#L37

Hi @anndvision, would appreciate if you could help me understand. 

I thought that CATE computation is simply the difference between predicted y_1 and y_0 - it appears that I do not understand it correctly. What are the mu_1 and mu_0 in this case?

The IHDP data also comes with y factual and counter factual but also mu1 and mu0 - what are their differences?

**Comment by anndvision** [comment]
Hi @jgamper,

Great questions! 

So, by definition the CATE estimator is the difference in expectations: 

<img src="https://render.githubusercontent.com/render/math?math=\widehat{\mathrm{CATE}}(\mathbf{x}) = \mathbb{E}[Y \mid T=1, \mathbf{X} = \mathbf{x}] - \mathbb{E}[Y \mid T=0, \mathbf{X} = \mathbf{x}]">

These expectations are here modelled using parameterised neural networks <img src="https://render.githubusercontent.com/render/math?math=\mu_{\omega_1}(\mathbf{x})"> and <img src="https://render.githubusercontent.com/render/math?math=\mu_{\omega_0}(\mathbf{x})">:

<img src="https://render.githubusercontent.com/render/math?math=\widehat{\mathrm{CATE}}_{\omega}(\mathbf{x}) = \mu_{\omega_1}(\mathbf{x}) - \mu_{\omega_0}(\mathbf{x}) ">.

Now, there may also be unexplained variance in <img src="https://render.githubusercontent.com/render/math?math=Y"> that is independent of both <img src="https://render.githubusercontent.com/render/math?math=X"> and <img src="https://render.githubusercontent.com/render/math?math=T">. 
In expectation, this reduces to some constant, and cancels out in the difference in expectations. 
That is, it has no effect on the CATE estimate. 

We can think of the unexplained variance in <img src="https://render.githubusercontent.com/render/math?math=Y"> as observation noise (though this is not entirely precise). A single observation <img src="https://render.githubusercontent.com/render/math?math=Y_i"> will be biased by such "noise". For the IHDP dataset, we train models on observations of y factual, which are biased by this "noise", and are what we would see in a real observational dataset. While the CATE (the difference in expectations) is identifiable, the individual treatment effect (y factual - y counter factual) is not. So the ground truth for IHDP is the difference in expectations (mu_1 - mu_0). 

Is this making sense?

**Comment by jgamper** [comment]
@anndvision thanks for the explanation! Yes, it is starting to make sense now! 

Right after asking the question, I found the section 5.2 from _[GANITE: Estimation of Individualized Treatment Effects using Generative Adversarial Nets](https://openreview.net/forum?id=ByKWUeWA-)_ where they discuss the difference between https://render.githubusercontent.com/render/math?math=\hat{\epsilon}_{PEHE} and https://render.githubusercontent.com/render/math?math=\epsilon_{PEHE} to be useful in pointing out that the difference is in the fact that the underlying data generating process is known so they can take the expectation (or as in this case have access to mu1 and mu0).

**Comment by jgamper** [comment]
@anndvision thanks for the explanation! Yes, it is starting to make sense now!

Right after asking the question, I found the section 5.2 from GANITE: Estimation of Individualized Treatment Effects using Generative Adversarial Nets where they discuss the difference between \hat{\epsilon}_{PEHE} and \epsilon_{PEHE} to be useful in pointing out that the difference is in the fact that the underlying data generating process is known so they can take the expectation (or as in this case have access to mu1 and mu0).
