### ISSUE TITLE
Package version freezing

### ISSUE THREAD

**Issue by HadarRosenwald** [OATML/ucate#6]
Hi @anndvision, when cloning the project and initiliazing the environment it installs the last version of each package. It leads to the following error:
```
ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.4; 
Detected an installation of version 2.3.2. Please upgrade TensorFlow to proceed.
```

I think freezing the package versions (in `setup.py`) might solve this and will allow running the project regardless of any future package releases.

For me, freezing the following versions helped:
```
        "tensorflow==2.3.1",
        "tensorflow-probability==0.11.1",
```
(but I think it's worth freezing all of them)

Thank you!

**Comment by anndvision** [comment]
@HadarRosenwald Thanks for pointing this out! I think what you have done makes sense. If you would like to make a PR with your changes, I would be very grateful. Otherwise, I will have time to address this after next Thursday.

**Comment by HadarRosenwald** [comment]
@anndvision Sure no problem! I created a PR

to be conservative, since I didn't check all project flows (I only ran tlearner with ihdp), I changed only the packages that their latest versions threw an error. The others I left untouched. LMK if that's ok or if you'd like anything else

Thank you!
